version: "3.9"
services:
  db:
    image: mysql:8.4
    container_name: sc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: sc_user
      MYSQL_PASSWORD: sc_pass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      retries: 5
      timeout: 5s

  api:
    image: node:20-alpine
    container_name: sc_api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run dev"

volumes:
  dbdata:
